/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

/* Header for class io_serniorzhao_as_ndk_MainActivity */

#ifndef _Included_io_serniorzhao_as_ndk_MainActivity
#define _Included_io_serniorzhao_as_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_serniorzhao_as_ndk_MainActivity
 * Method:    testLog
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_io_serniorzhao_as_1ndk_MainActivity_testLog
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
